# Generated by Django 4.1.7 on 2023-03-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misjuegos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='fecha',
            field=models.CharField(max_length=10),
        ),
    ]
