# Generated by Django 4.1.5 on 2023-03-25 20:43

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misjuegos', '0002_alter_juego_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='fecha',
        ),
        migrations.AddField(
            model_name='juego',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='estudio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='tematica',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='titulo',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
